Add ANSIBLE_RUNNER_DEBUG_CMD
openstack-k8s-operators/openstack-ansibleee-operator pull request #146
Opened 2023-04-29 01:06 UTC by dprince

Setting this env will allow the administrator to override the default ansible command to use with arbitrary ansible job commands. Potentially useful for mocked out testing for scale...

2023-05-02 09:50 UTC, fao89 approved these changes

2023-05-02 13:05 UTC, slagle approved these changes

2023-05-02 13:09 UTC, fao89 commented
/test ansibleee-operator-build-deploy-kuttl
recheck

2023-05-02 15:36 UTC, slagle requested changes

2023-05-02 15:36 UTC, slagle commented on controllers/openstack_ansibleee_controller.go
> +	if len(r.AnsibleRunnerDebugCmd) != 0 {
This handling is failing the CI. The length here is 1, not 0 when strings.Split is run against the empty string. I won't claim that I knew that before having to look on stackoverflow :).

https://stackoverflow.com/questions/35866221/why-does-an-empty-array-returned-from-strings-split-have-a-length-of-1-in-golang

This results in the generated pod YAML having an empty command:

https://logserver.rdoproject.org/46/146/83e55987268b8fd241a80cbb3074ac0c3d52225b/github-check/openstack-ansibleee-operator-github-rdo-integration-centos-8-crc-singlenode-centos-9-external-compute/06a291d/controller/controller/pod/deploy-external-dataplane-compute-kmmf5.yaml

And the error:

          container create failed: time="2023-04-29T02:06:55Z" level=error msg="runc create failed: unable to start container process: exec: \"\": executable file not found in $PATH"

2023-08-31 11:06 UTC, slagle commented
Please re-open if this is still needed.

2023-08-31 11:06 UTC, closed without merging